import Head from 'next/head';
import { GetStaticProps } from 'next';

type Props = { timestamp: number };

export default function ISR(props: Props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>ISRページ</h1>
        <p> time: {props.timestamp}</p>
      </main>
    </div>
  )
};

export const getStaticProps: GetStaticProps<Props> = async context => {
  return {
    props: {
      timestamp: new Date().getTime(),
    },
    revalidate: 5, // 5 seconds cache
  }
};
